Add no-dry-run option

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -4,7 +4,14 @@
 # 1. create a config
 #   prompt for values and save
 # view, edit, delete, list, run
-#
+
+# potional:
+#     backup config file
+# options:
+#   -n, --no-dry-run (sync only)
+#   -r, --reverse (sync only)
+# maybe overrides for backups
+
 # declare TITLE="Example Backup"
 # declare DESCRIPTION="This is just an example."
 # declare BACKUP_NAME="example_backup"
@@ -13,6 +20,38 @@
 # declare DESTINATION="$HOME/mybackups"
 # declare WORKING_PATH="$HOME/Pictures"
 # declare EXCLUDE='Screenshots'
+
+ParseArgs() {
+    while test $# -gt 0; do
+        _KEY="$1"
+        case "$_KEY" in
+            -n|--no-dry-run)
+                DRY_RUN=""
+                ;;
+            -h|--help)
+                Help
+                exit 0
+                ;;
+            -v|--version)
+                echo "put version here"
+                exit 0
+                ;;
+            -*|--*)
+                echo "Unknown argument: $_KEY"
+                exit 1
+                ;;
+            *)  # One positional, backup file
+                BACKUP_CONFIG=$1
+                if [ ! -f $BACKUP_CONFIG ]; then
+                    echo "Backup configuration file not found: $BACKUP_CONFIG"
+                    exit 1
+                fi
+                ;;
+        esac
+        shift
+    done
+}
+
 
 Help() {
     echo "
@@ -57,12 +96,13 @@ ShortHelp() {
 
 
 CheckInputs() {
-    echo "  Validating backup parameters.."
+    # Validate configuration file inputs
+    # Change to working directory if given
     if [ -z $BACKUP_TYPE ]; then
         echo "Error - Missing required backup type"
     else
-        if [ ! $BACKUP_TYPE = "ARCHIVE" ] && [ ! $BACKUP_TYPE = "SYNC" ]; then
-            echo "Error - Invalid backup type: $BACKUP_TYPE"
+        if [ $BACKUP_TYPE != "ARCHIVE" ] && [ $BACKUP_TYPE != "SYNC" ]; then
+            echo "Error - Invalid backup type: '$BACKUP_TYPE'"
             echo "  Valid types: ARCHIVE or SYNC"
             exit 1
         fi
@@ -110,10 +150,10 @@ ArchiveBackup() {
         --gzip \
         --verbose \
         --file=$BACKUP_PATH \
-        --exclude=$EXCLUDE \
+        --exclude-from=$EXCLUDE_FILE \
         $SOURCE
     if [ $? -eq 0 ]; then
-        echo "Backup complete. File saved to"
+        echo "Backup complete."
         echo "  $BACKUP_PATH"
     else
         echo "Error - creating backup file"
@@ -122,47 +162,50 @@ ArchiveBackup() {
 
 
 SyncBackup() {
-    echo "Sync backup, coming to a Linux distro near you!"
+    echo "Starting sync.."
+    #rsync -avhn --exclude-from exclude.lst --delete-after /media/orth/backup/Library/ /mnt/shared/Library/ | tee $HOME/Desktop/log.txt
+    rsync \
+        --archive \
+        --delete-after \
+        --exclude-from="$EXCLUDE_FILE" \
+        --human-readable \
+        --verbose \
+        $DRY_RUN \
+        $SOURCE \
+        $DESTINATION \
+        | tee $LOG_FILE
+    if [ $? -eq 0 ]; then
+        echo "Sync complete."
+    else
+        echo "Error syncing"
+        echo "  $SOURCE"
+        echo "  $DESTINATION"
+    fi
 }
 
 
-##############################################
-#                    Main                    #
-##############################################
+#####################################################################
+#                                Main                               #
+#####################################################################
 declare BACKUP_EXT=".tar.gz"
 declare DATE_TIME=$(date +"%Y%m%d_%H%M%S")
+declare DRY_RUN="--dry-run"
 
-# Check arguments
-if [ $# -eq 0 ]; then
-    echo "Where are the arguments?"
-    exit 1
-elif [ $# -eq 1 ]; then
-    if [ ! -f $1 ]; then
-        echo "Error - Backup config file does not exist:"
-        echo "  $1"
-        exit 1
-    fi
-    BACKUP_FILE=$1
-else
-    echo "You don't know how to use this, do you?"
-    exit 1
-fi
-
-echo "Setting up backup.."
-
-source $BACKUP_FILE
+ParseArgs "$@"
+echo "Reading configuration file.."
+source $BACKUP_CONFIG
 CheckInputs
 BACKUP_PATH=${DESTINATION}/${BACKUP_NAME}_${DATE_TIME}${BACKUP_EXT}
-
-echo "  Title: $TITLE"
-echo "  Description: $DESCRIPTION"
+printf 'Title:\n  %s\n' "$TITLE"
+printf 'Description:\n  %s\n' "$DESCRIPTION"
 
 if [ $BACKUP_TYPE = "ARCHIVE" ]; then
     ArchiveBackup
-elif [ $BACKUP_TYPE = "SYNC " ]; then
+elif [ $BACKUP_TYPE = "SYNC" ]; then
     SyncBackup
 else
-    echo "Error - Invalid backup type: $BACKUP_TYPE"
+    echo "Error - Bad backup type: '$BACKUP_TYPE'"
+    exit 1
 fi
 
 exit 0
